apiVersion: apps/v1
kind: Deployment
metadata:
  name: detect-delivery
spec:
  selector:
    matchLabels:
      app: detect-delivery
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: detect-delivery
    spec:
      containers:
      - name: detect-delivery
        image: jroshanucb/detect_delivery:latest
        volumeMounts:
        - mountPath: /home/nvidia/project
          name: home
        securityContext:
          privileged: true
      volumes:
      - name: home
        hostPath:
          path: /home/nvidia/project