apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-publisher
spec:
  selector:
    matchLabels:
      app: test-publisher
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: test-publisher
    spec:
      containers:
      - name: detector
        image: jroshanucb/test-publisher
        volumeMounts:
        - mountPath: /home/nvidia/project/images
          name: home
        securityContext:
          privileged: true
      volumes:
      - name: home
        hostPath:
          path: /home/nvidia/project/images
