apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-rec
spec:
  selector:
    matchLabels:
      app: face-rec
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: face-rec
    spec:
      containers:
      - name: face-rec
        image: stevendleung/face_rec
        volumeMounts:
        - mountPath: /data/door_cam_images
          name: door-cam-images
        securityContext:
          privileged: true
      volumes:
      - name: door-cam-images
        hostPath:
          path: /data/door_cam_images