apiVersion: apps/v1
kind: Deployment
metadata:
  name: detector
spec:
  selector:
    matchLabels:
      app: detector
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: detector
    spec:
      containers:
      - name: detector
        image: jramirez0508/detector:latest
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
        securityContext:
          privileged: true
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0
